### ISSUE TITLE
Adding Contributors in README file and adding LICENSE file

### ISSUE THREAD

**Issue by PeritusDeveloper** [ProgramingIsTheFuture/Dyri#20]
### Proposed Changes
- Acknowledge the Contributing by mentioning them in README along with their profile pictures.
- The list automatically gets updated when there PR is merged.
- Adding LICENSE.md to claim the hard work done in the project as owner's
- Adding Copyright Logo at end of README file

**Comment by ProgramingIsTheFuture** [comment]
Hello, thank you for the suggestion. Can you handle it? 😃

**Comment by PeritusDeveloper** [comment]
Yes I want to do this
Please assign it to me
